# Generated by Django 6.0.4 on 2026-05-02 09:04

import django.db.models.deletion
import pm_auth.api.users.auth.external_token.token
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAuthenticationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('provider', models.CharField(choices=[('WH', 'WhatsApp'), ('SMS', 'SMS'), ('D', 'Console')], default='SMS', max_length=5)),
                ('type', models.CharField(choices=[('VA', 'Validate account'), ('SI', 'Sign in'), ('RP', 'Reset password'), ('RA', 'Recover account')], default='SI', max_length=5)),
                ('token', models.CharField(blank=True, default=pm_auth.api.users.auth.external_token.token.random_token, max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_authentication_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
